config/routes.rb
Rails.application.routes.draw do

  resources :wishlists
   mount LetsencryptPlugin::Engine, at: '/'  # It must be at root level


  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}, :skip => [:registrations]
  
  devise_scope :user do
    match 'users/:id' => 'users/registrations#destroy', :via => :delete, :as => :admin_destroy_user
    post 'modal_edit_user' => 'users/registrations#modal_edit_user', :as => 'modal_edit_user'
    post 'modal_create_user' => 'users/registrations#modal_create_user', :as => 'modal_create_user'
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'    
    patch 'users' => 'users/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 resources :books
 resources :publishers
 resources :authors

 get 'static_pages/home'
 get '/uzivatelia' => 'static_pages#users', :as => 'users'

 #authors
 post '/modal_create_author' => 'authors#modal_create_author', :as=> 'modal_create_author'
 post '/modal_edit_author' => 'authors#modal_edit_author', :as=> 'modal_edit_author'
  
 #publishers
 post '/modal_create_publisher' => 'publishers#modal_create_publisher', :as=> 'modal_create_publisher'
 post '/modal_edit_publisher' => 'publishers#modal_edit_publisher', :as=> 'modal_edit_publisher'

 #books
 post '/modal_create_book' => 'books#modal_create_book', :as=> 'modal_create_book'
 post '/modal_edit_book' => 'books#modal_edit_book', :as=> 'modal_edit_book'
 get '/chart_total_books' => 'books#chart_total_books', :as=> 'chart_total_books'
 get '/chart_top_book_publishers' => 'books#chart_top_book_publishers', :as=> 'chart_top_book_publishers'
 get '/chart_top_book_authors' => 'books#chart_top_book_authors', :as=> 'chart_top_book_authors'

#wishlists
post '/modal_create_wishlist' => 'wishlists#modal_create_wishlist', :as=> 'modal_create_wishlist'
post '/modal_edit_wishlist' => 'wishlists#modal_edit_wishlist', :as=> 'modal_edit_wishlist'
post '/update_from_martinus' => 'wishlists#update_from_martinus', :as=> 'update_from_martinus'
post '/move_from_wishlist' => 'wishlists#move_from_wishlist', :as=> 'move_from_wishlist'
get '/chart_total_wishlist' => 'wishlists#chart_total_wishlist', :as=> 'chart_total_wishlist'

  root 'static_pages#home'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def users
		@users = User.all
	end
	
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	def get_book_count
		Book.all.count
	end
end

app/views/static_pages/home.html.erb
<p id="notice"><%= render 'layouts/flash_message' %></p>
<%= javascript_include_tag 'charts' , 'data-turbolinks-track' => true %>

<h1>Ahoj <%= current_user.name %>, v knižnici je aktuálne <strong><%= get_book_count %></strong> kníh</h1>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div id="spinner_box" style="display:none">
          <div class="sk-spinner sk-spinner-wave" >
                         <div class="sk-rect1"></div>
                                <div class="sk-rect2"></div>
                                <div class="sk-rect3"></div>
                                <div class="sk-rect4"></div>
                                <div class="sk-rect5"></div>
                            </div>
                </div>

   <div class="col-lg-12 main-box">
     <div class="ibox float-e-margins">
      <div class="ibox-content">
		

				<div class="panel-body">
										
					<div id="data1">
				
						
						
						<div class="row">
							 <div class="col-sm-6 text-center">
						       <label class="label label-success">Knihy v knižnici</label>
						      <div id="piechartbooks" ></div>
						    </div>
						    <div class="col-sm-6 text-center">
						       <label class="label label-success">Knihy vo wishliste</label>
						      <div id="piechartwishlist" ></div>
						    </div>
					
					</div>
					<hr>
					<div class="row">
						<div  class="col-sm-12 text-center">
					       <label class="label label-success">Top vydavatelia</label>
					      <div id="barchartpublishers" ></div>
					    </div>
					</div>
					<hr>
					<div class="row">
						<div  class="col-sm-12 text-center">
					       <label class="label label-success">Top autori</label>
					      <div id="barchartauthors" ></div>
					    </div>
					</div>
	
			</div>

		</div>








	</div>
</div>
</div>
</div>
</div>


<script>




var ready = function() {



 $.ajax({
        url : '/chart_total_books.json',    
    }).done(function(data){
    	if (data.status == 'ok'){
    		    		
    	//console.log(data)
        Morris.Donut({
          element: 'piechartbooks',
          data: JSON.parse(data.data),
           resize: true,
           colors: ['#87d6c6', '#1c84c6']
        });
    	}
    	else {
    		$("#notice").html(flashMessageFromAjax('Nepodarilo sa natiahnuť údaje do grafov'));
    	}

    }).fail(function(){
    	$("#notice").html(flashMessageFromAjax('Nepodarilo sa natiahnuť údaje do grafov'));
    });


 $.ajax({
        url : '/chart_total_wishlist.json',    
    }).done(function(data){
    	if (data.status == 'ok'){
    		    		
    	//console.log(data)
        Morris.Donut({
          element: 'piechartwishlist',
          data: JSON.parse(data.data),
           resize: true,
           colors: ['#87d6c6', '#1c84c6']
        });
    	}
    	else {
    		$("#notice").html(flashMessageFromAjax('Nepodarilo sa natiahnuť údaje do grafov'));
    	}

    }).fail(function(){
    	$("#notice").html(flashMessageFromAjax('Nepodarilo sa natiahnuť údaje do grafov'));
    });


  $.ajax({
        url : '/chart_top_book_publishers.json',    
    }).done(function(data){
    	if (data.status == 'ok'){
    		    		
    	//console.log(data)
        Morris.Bar({
		  element: 'barchartpublishers',
		  data: JSON.parse(data.data),
		  xkey: 'publisher_name',
		  barColors: ['#87d6c6'],
		  resize: true,
		  ykeys: ['value'],
		  labels: ['Počet kníh']
		});
    	}
    	else {
    		$("#notice").html(flashMessageFromAjax('Nepodarilo sa natiahnuť údaje do grafov'));
    	}

    }).fail(function(){
    	$("#notice").html(flashMessageFromAjax('Nepodarilo sa natiahnuť údaje do grafov'));
    });

   $.ajax({
        url : '/chart_top_book_authors.json',    
    }).done(function(data){
    	if (data.status == 'ok'){
    		    		
    	//console.log(data)
        Morris.Bar({
		  element: 'barchartauthors',
		  data: JSON.parse(data.data),
		  barColors: [ '#1c84c6'],
		  xkey: 'author_name',
		  resize: true,
		  ykeys: ['value'],
		  labels: ['Počet kníh']
		});
    	}
    	else {
    		$("#notice").html(flashMessageFromAjax('Nepodarilo sa natiahnuť údaje do grafov'));
    	}

    }).fail(function(){
    	$("#notice").html(flashMessageFromAjax('Nepodarilo sa natiahnuť údaje do grafov'));
    });

 

};
 



$(".static_pages.home").ready(ready);

document.addEventListener('turbolinks:before-cache', function() {
 $('#piechartbooks').empty();
$('#piechartwishlist').empty();
$('#barchartpublishers').empty();
$('#barchartauthors').empty();


});

$(".static_pages.home").on('turbolinks:load', ready);

</script>

app/views/static_pages/users.html.erb
<p id="notice"><%= render 'layouts/flash_message' %></p>

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Užívatelia</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to 'Home', root_path %>
      </li>
      <li class="active">
        <strong>Užívatelia</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">

  </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row margin35minus">
   <div class="col-lg-12 nopadding">
     <div class="ibox float-e-margins">
      <div class="ibox-content">
        <button type="button" class="btn btn-success" id="add_contact_button" data-toggle="modal" data-target="#addUserModal">Pridaj nového užívateľa</button>
        
        <hr>
        <div class="table-responsive">
          <table class="table table-bordered" id="users" style="width:100%">
            <thead>
              <tr>
                <th>Užívateľ</th>
                <th>Email</th>
                <th>Typ</th>
                
        
                <th></th>
               
              </tr>
            </thead>
            <tbody>
               <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><% if user.admin? %>Správca<% else %>Bežný užívateľ<% end %></td>
      
        
        <td><%= link_to admin_destroy_user_path(user), method: :delete, data: { confirm: 'Naozaj ho chceš zmazať?' } do %><i class="fa fa-trash-o fa-2x" aria-hidden="true" ></i>  
                <% end %></td>
        
      </tr>
    <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<br>

<div id="addUserModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h2 class="modal-title" id="myModalLabel">Vytvor užívateľa </h2>
       
      </div>
      <div class="modal-body">
        <div class="form-group has-error">
         <label>Email:</label><input type="text" name="adduseremail" id="adduseremail" class="form-control" placeholder="Email" /><br>
          <label>Meno:</label><input type="text" name="addusername" id="addusername" class="form-control" placeholder="Meno" /><br>
        
            <label>Heslo:</label><input type="password" name="password" id="password" class="form-control" /><br>
            <label>Zopakuj heslo:</label><input type="password" name="password_confirm" id="password_confirm" class="form-control" /><br>

           
       </div>
       <button id="adduserconfirm" type="button" class="addusr btn btn-success">Vytvor</button>
 
   </div>
 </div>
</div>
</div>





<script>
var userstable;

var tableready = function() {



 userstable= $('#users').DataTable({
  'order': [2, 'desc'],
  'serverSide': false,
  'stateSave' :true,
  'dom': 'lfr<"pull-right">tip',
 /* 'buttons': [
  {"extend" : 'copyHtml5',"text":"Copy","className": 'btn btn-default btn-xs'},
  {"extend" : 'excelHtml5',"text": "XLS","className": 'btn btn-default btn-xs'},
  {"extend" : 'csvHtml5',"text": "CSV","className": 'btn btn-default btn-xs'},

  {
    text: 'TXT',
    extend: 'csvHtml5',
    fieldSeparator: '\t',
    extension: '.txt',
    "className": 'btn btn-default btn-xs'
  },
  {"extend" : 'pdfHtml5',"text": "PDF","className": 'btn btn-default btn-xs'},

  ],*/
  'language': {
        'url': '/datatables_slovak.json'
      },
  'lengthMenu': [
  [10, 50,100, -1],
  [10, 50,100, "All"]
  ]

});


$('.editusr').on('click',function(event){
          //console.log(event.target.id);
          
          $user_id = event.target.id;
          $user_name = $('#username'+$user_id).val();
          $user_type = $('#usertype'+$user_id).val();

              $.ajax({
            type: "POST",
            url: "/modal_edit_user",
            data: {user_id: $user_id, user_type: $user_type, user_name: $user_name},

            success:function(data){
              if (data.status == "ok")
              {
                alert("Užívateľ bol upravený" );
                location.reload();
              }
              else { alert("Error");}


            }
          });
          



        });

$('.addusr').on('click',function(event){
          //console.log(event.target.id);
          
          $user_email = $('#adduseremail').val();
          $user_name = $('#addusername').val();
          $user_type = $('#addusertype').val();
          $password = $('#password').val();
          $password_confirm = $('#password_confirm').val();

              $.ajax({
            type: "POST",
            url: "/modal_create_user",
            data: {
              user_type: $user_type,
              user_name: $user_name,
              user_email: $user_email,
              password: $password,
              password_confirm: $password_confirm},

            success:function(data){
              if (data.status == "ok")
              {
                alert("Užívateľ bol vytvorený" );
                location.reload();
              }
              else { alert(data.status);}


            }
          });
          



        });


};
$(".static_pages.users").ready(tableready);


document.addEventListener('turbolinks:before-cache', function() {
 if ($('#users_wrapper').length ==1) {userstable.destroy() ;} 

});


$(".static_pages.users").on('turbolinks:load', tableready); 
</script>