config/routes.rb
Rails.application.routes.draw do

  resources :wishlists
   mount LetsencryptPlugin::Engine, at: '/'  # It must be at root level


  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}, :skip => [:registrations]
  
  devise_scope :user do
    match 'users/:id' => 'users/registrations#destroy', :via => :delete, :as => :admin_destroy_user
    post 'modal_edit_user' => 'users/registrations#modal_edit_user', :as => 'modal_edit_user'
    post 'modal_create_user' => 'users/registrations#modal_create_user', :as => 'modal_create_user'
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'    
    patch 'users' => 'users/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 resources :books
 resources :publishers
 resources :authors

 get 'static_pages/home'
 get '/uzivatelia' => 'static_pages#users', :as => 'users'

 #authors
 post '/modal_create_author' => 'authors#modal_create_author', :as=> 'modal_create_author'
 post '/modal_edit_author' => 'authors#modal_edit_author', :as=> 'modal_edit_author'
  
 #publishers
 post '/modal_create_publisher' => 'publishers#modal_create_publisher', :as=> 'modal_create_publisher'
 post '/modal_edit_publisher' => 'publishers#modal_edit_publisher', :as=> 'modal_edit_publisher'

 #books
 post '/modal_create_book' => 'books#modal_create_book', :as=> 'modal_create_book'
 post '/modal_edit_book' => 'books#modal_edit_book', :as=> 'modal_edit_book'
 get '/chart_total_books' => 'books#chart_total_books', :as=> 'chart_total_books'
 get '/chart_top_book_publishers' => 'books#chart_top_book_publishers', :as=> 'chart_top_book_publishers'
 get '/chart_top_book_authors' => 'books#chart_top_book_authors', :as=> 'chart_top_book_authors'

#wishlists
post '/modal_create_wishlist' => 'wishlists#modal_create_wishlist', :as=> 'modal_create_wishlist'
post '/modal_edit_wishlist' => 'wishlists#modal_edit_wishlist', :as=> 'modal_edit_wishlist'
post '/update_from_martinus' => 'wishlists#update_from_martinus', :as=> 'update_from_martinus'
post '/move_from_wishlist' => 'wishlists#move_from_wishlist', :as=> 'move_from_wishlist'
get '/chart_total_wishlist' => 'wishlists#chart_total_wishlist', :as=> 'chart_total_wishlist'

  root 'static_pages#home'
end

app/models/author.rb
class Author < ApplicationRecord
	has_many :books,:dependent => :destroy
	validates :name, :presence => true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  def modal_create_author
    begin

     authname=params[:authname]
     authcountry=params[:authcountry]
     birthyear=params[:birthyear]
     deadyear=params[:deadyear]
    


     a=Author.new(:name=>authname, :country=>authcountry, :birth_year=>birthyear, :dead_year=> deadyear)
    
    if (a.save)

      respond_to do |format|
        format.json { render :json => {"status":"ok"}  }
      end
    else
      respond_to do |format|
        format.json { render :json => {"status":"nepodarilo sa vložiť záznam"}  }
      end
    end



  rescue => error
    redirect_to authors_path, alert: error.message
  end
  end

  def modal_edit_author
    begin

      @author = Author.find(params[:authorID])

     @author.name=params[:authname]
     @author.country=params[:authcountry]
     @author.birth_year=params[:birthyear]
     @author.dead_year=params[:deadyear]
    


     
    
    if (@author.save)

      respond_to do |format|
        format.json { render :json => {"status":"ok"}  }
      end
    else
      respond_to do |format|
        format.json { render :json => {"status":"nepodarilo sa vložiť záznam"}  }
      end
    end



  rescue => error
    redirect_to authors_path, alert: error.message
  end
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Autor bol úspešne zmazaný.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :country, :birth_year, :dead_year)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :birth_year %>
    <%= form.number_field :birth_year %>
  </div>

  <div class="field">
    <%= form.label :dead_year %>
    <%= form.number_field :dead_year %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= render 'layouts/flash_message' %></p>

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Autori</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to 'Home', root_path %>
      </li>
      <li class="active">
        <strong>Autori</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">

  </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row margin35minus">
   <div class="col-lg-12 nopadding">
     <div class="ibox float-e-margins">
      <div class="ibox-content">
        <button type="button" class="btn btn-success" id="add_author_button" data-toggle="modal" data-target="#addAuthorModal">Pridaj nového autora</button>
        
        <hr>
        <div class="table-responsive">
          <table class="table table-bordered" id="authors" style="width:100%">
  <thead>
    <tr>
      <th class="hidden">ID</th>
      <th>Meno</th>
      <th>Krajina</th>
      <th>Rok narodenia</th>
      <th>Rok úmrtia</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td class="hidden"><%= author.id %></td>
        <td><%= author.name %></td>
        <td><%= author.country %></td>
        <td><%= author.birth_year %></td>
        <td><%= author.dead_year %></td>
        

        <td><a class="edit_author_table_btn" data-toggle="modal" data-target="#editAuthorModal"><i id="<%=author.id%>" class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i></a></td>
        <td><%= link_to  author, method: :delete, data: { confirm: 'Naozaj ho chceš zmazať?' } do %><i class="fa fa-trash-o fa-2x" aria-hidden="true" ></i>  
                <% end %></td>

         
        
      </tr>
    <% end %>
  </tbody>
 </table>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<br>

<div id="addAuthorModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h2 class="modal-title" id="myModalLabel">Pridaj autora </h2>
       
      </div>
      <div class="modal-body">
        <div class="alert alert-danger noborders">
   Polia vyznačené na červeno sú povinné
  </div>
        <div class="form-group has-error">
            <label>Meno:</label><input type="text" name="authorname" id="authorname" class="form-control" placeholder="Meno" /><br>
            </div>
            <label>Krajina:</label><input type="text" name="authorcountry" id="authorcountry" class="form-control" placeholder="Krajina" /><br>
            <label>Rok narodenia:</label><input type="number" name="authorbirth" id="authorbirth" class="form-control" placeholder="Zadaj rok" /><br>
            <label>Rok úmrtia:</label><input type="number" name="authordeath" id="authordeath" class="form-control" placeholder="Zadaj rok" /><br>
           
       
       <button id="addauthorconfirm" type="button" class="addauthor btn btn-success">Pridaj</button>
 
   </div>
 </div>
</div>
</div>

<div id="editAuthorModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h2 class="modal-title" id="myModalLabel">Uprav autora </h2>
       
      </div>
      <div class="modal-body">
        <div class="alert alert-danger noborders">
   Polia vyznačené na červeno sú povinné
  </div>
        <div class="form-group has-error">
           <input style="visibility:hidden" type="text" name="editauthorID" id="editauthorID" value="" readonly>
            <label>Meno:</label><input type="text" name="edit_authorname" id="edit_authorname" class="form-control" placeholder="Meno" /><br>
            </div>
            <label>Krajina:</label><input type="text" name="edit_authorcountry" id="edit_authorcountry" class="form-control" placeholder="Krajina" /><br>
            <label>Rok narodenia:</label><input type="number" name="edit_authorbirth" id="edit_authorbirth" class="form-control" placeholder="Zadaj rok" /><br>
            <label>Rok úmrtia:</label><input type="number" name="edit_authordeath" id="edit_authordeath" class="form-control" placeholder="Zadaj rok" /><br>
           
       
       <button id="editauthorconfirm" type="button" class="editauthor btn btn-success">Uprav</button>
 
   </div>
 </div>
</div>
</div>

<script>
var authortable;

var tableready = function() {



 authortable= $('#authors').DataTable({
  'order': [2, 'desc'],
  'serverSide': false,
  'stateSave' :true,
  'dom': 'lfr<"pull-right">tip',
 /* 'buttons': [
  {"extend" : 'copyHtml5',"text":"Copy","className": 'btn btn-default btn-xs'},
  {"extend" : 'excelHtml5',"text": "XLS","className": 'btn btn-default btn-xs'},
  {"extend" : 'csvHtml5',"text": "CSV","className": 'btn btn-default btn-xs'},

  {
    text: 'TXT',
    extend: 'csvHtml5',
    fieldSeparator: '\t',
    extension: '.txt',
    "className": 'btn btn-default btn-xs'
  },
  {"extend" : 'pdfHtml5',"text": "PDF","className": 'btn btn-default btn-xs'},

  ],*/
  'language': {
        'url': '/datatables_slovak.json'
      },
  'lengthMenu': [
  [10, 50,100, -1],
  [10, 50,100, "All"]
  ]

});

 $('.edit_author_table_btn').on('click',function(event){
  //$author_id=event.target.id;
  $("#editauthorID").val(event.target.id);
  $row = $(event.target).closest('tr');
  $("#edit_authorname").val($("td:eq(1)",$row).text());
  $("#edit_authorcountry").val($("td:eq(2)",$row).text())
  $("#edit_authorbirth").val($("td:eq(3)",$row).text())
  $("#edit_authordeath").val($("td:eq(4)",$row).text())



 });


$('.editauthor').on('click',function(event){
          //console.log(event.target.id);
          
          $author_id = $("#editauthorID").val();
          $authname = $('#edit_authorname').val();
          $authcountry = $('#edit_authorcountry').val();
          $birthyear = $('#edit_authorbirth').val();
          $deadyear = $('#edit_authordeath').val();

              $.ajax({
            type: "POST",
            url: "/modal_edit_author",
             data: {
              authorID: $author_id,
              authname: $authname,
              authcountry: $authcountry,
              birthyear: $birthyear,
              deadyear: $deadyear},

            success:function(data){
              if (data.status == "ok")
              {
                alert("Autor bol upravený" );
                location.reload();
              }
              else { alert("Error");}


            }
          });
          



        });

$('.addauthor').on('click',function(event){
          //console.log(event.target.id);
          
          $authname = $('#authorname').val();
          $authcountry = $('#authorcountry').val();
          $birthyear = $('#authorbirth').val();
          $deadyear = $('#authordeath').val();
          

              $.ajax({
            type: "POST",
            url: "/modal_create_author",
            data: {
              authname: $authname,
              authcountry: $authcountry,
              birthyear: $birthyear,
              deadyear: $deadyear},

            success:function(data){
              if (data.status == "ok")
              {
                alert("Autor bol vytvorený" );
                location.reload();
              }
              else { alert(data.status);}


            }
          });
          



        });


};
$(".authors.index").ready(tableready);


document.addEventListener('turbolinks:before-cache', function() {
 if ($('#authors_wrapper').length ==1) {authortable.destroy() ;} 

});


$(".authors.index").on('turbolinks:load', tableready); 
</script>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @author.country %>
</p>

<p>
  <strong>Birth year:</strong>
  <%= @author.birth_year %>
</p>

<p>
  <strong>Dead year:</strong>
  <%= @author.dead_year %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>