config/routes.rb
Rails.application.routes.draw do

  resources :wishlists
   mount LetsencryptPlugin::Engine, at: '/'  # It must be at root level


  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}, :skip => [:registrations]
  
  devise_scope :user do
    match 'users/:id' => 'users/registrations#destroy', :via => :delete, :as => :admin_destroy_user
    post 'modal_edit_user' => 'users/registrations#modal_edit_user', :as => 'modal_edit_user'
    post 'modal_create_user' => 'users/registrations#modal_create_user', :as => 'modal_create_user'
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'    
    patch 'users' => 'users/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 resources :books
 resources :publishers
 resources :authors

 get 'static_pages/home'
 get '/uzivatelia' => 'static_pages#users', :as => 'users'

 #authors
 post '/modal_create_author' => 'authors#modal_create_author', :as=> 'modal_create_author'
 post '/modal_edit_author' => 'authors#modal_edit_author', :as=> 'modal_edit_author'
  
 #publishers
 post '/modal_create_publisher' => 'publishers#modal_create_publisher', :as=> 'modal_create_publisher'
 post '/modal_edit_publisher' => 'publishers#modal_edit_publisher', :as=> 'modal_edit_publisher'

 #books
 post '/modal_create_book' => 'books#modal_create_book', :as=> 'modal_create_book'
 post '/modal_edit_book' => 'books#modal_edit_book', :as=> 'modal_edit_book'
 get '/chart_total_books' => 'books#chart_total_books', :as=> 'chart_total_books'
 get '/chart_top_book_publishers' => 'books#chart_top_book_publishers', :as=> 'chart_top_book_publishers'
 get '/chart_top_book_authors' => 'books#chart_top_book_authors', :as=> 'chart_top_book_authors'

#wishlists
post '/modal_create_wishlist' => 'wishlists#modal_create_wishlist', :as=> 'modal_create_wishlist'
post '/modal_edit_wishlist' => 'wishlists#modal_edit_wishlist', :as=> 'modal_edit_wishlist'
post '/update_from_martinus' => 'wishlists#update_from_martinus', :as=> 'update_from_martinus'
post '/move_from_wishlist' => 'wishlists#move_from_wishlist', :as=> 'move_from_wishlist'
get '/chart_total_wishlist' => 'wishlists#chart_total_wishlist', :as=> 'chart_total_wishlist'

  root 'static_pages#home'
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :author, optional: true
	belongs_to :publisher, optional: true
	belongs_to :user
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: [:show, :edit, :update, :destroy]

  # GET /wishlists
  # GET /wishlists.json
  def index
    @wishlists = Wishlist.all
    @authors = Author.all.order(:name)
    @publishers = Publisher.all.order(:name)
  end

  # GET /wishlists/1
  # GET /wishlists/1.json
  def show
  end

  # GET /wishlists/new
  def new
    @wishlist = Wishlist.new
  end

  # GET /wishlists/1/edit
  def edit
  end

def modal_create_wishlist
    begin

     name=params[:name]
     author=params[:author]
     publisher = params[:publisher]
     publish_year = params[:publish_year]
     note = params[:note]
     martinus_url = params[:martinus_url]
     
    w=Wishlist.new(:name=>name, :author_id=>author, :publisher_id=>publisher, :note=>note, :publish_year=>publish_year, :user_id=>current_user.id, :martinus_url=>martinus_url)
    
    if (w.save)

      respond_to do |format|
        format.json { render :json => {"status":"ok"}  }
      end
    else
      respond_to do |format|
        format.json { render :json => {"status":"nepodarilo sa vložiť záznam"}  }
      end
    end



    rescue => error
      redirect_to wishlists_path, alert: error.message
    end
  end


def modal_edit_wishlist
    begin

      @wishlist = Wishlist.find(params[:wishlistID])

      @wishlist.name=params[:name]
      @wishlist.author_id=params[:author]
      @wishlist.publisher_id = params[:publisher]
      @wishlist.publish_year = params[:publish_year]
      @wishlist.note = params[:note]
      @wishlist.martinus_url = params[:martinus_url]
     
    
    
    if (@wishlist.save)

      respond_to do |format|
        format.json { render :json => {"status":"ok"}  }
      end
    else
      respond_to do |format|
        format.json { render :json => {"status":"nepodarilo sa vložiť záznam"}  }
      end
    end



  rescue => error
    redirect_to wishlists_path, alert: error.message
  end
  end

def update_from_martinus
  require 'nokogiri'
  require 'openssl'
  require 'open-uri'
  require 'json'
  begin
      @wishlists = Wishlist.all

      @wishlists.each do |wishlist|
        #page = Nokogiri::XML(open(wishlist.martinus_url))
        page = Nokogiri::HTML(open(wishlist.martinus_url))

        #book_data = page.xpath('//script[@type="application/ld+json"][1]').text
        book_data = page.at('script[type="application/ld+json"]').text
        preorder_data = page.xpath('//div[@class="card__content"]/p[@class="mb-small text-color-grey-dark"]').text

        json_book_data = JSON.parse(book_data)

        publisher_name = ''
        json_book_data["publisher"].each do |publisher|
          publisher_name = publisher["name"]
        end

        author_name = ''

        json_book_data["author"].each do |author|
          author_name = author["name"]
        end

        price = json_book_data["offers"]["price"]
        currency = json_book_data["offers"]["priceCurrency"]
        final_price = (price.to_s) +' '+(currency.to_s)
        

        @author = Author.where(:name=>author_name.strip).first_or_create
        @publisher = Publisher.where(:name=>publisher_name.strip).first_or_create

        if preorder_data.present?
          expected_release = preorder_data
        else
          expected_release = 'Už vydané alebo bude čoskoro'
        end


          wishlist.name = json_book_data["name"]
          wishlist.pages = json_book_data["numberOfPages"]
          wishlist.image_url = json_book_data["thumbnailUrl"]
          wishlist.author_id = @author.id
          wishlist.publisher_id = @publisher.id
          wishlist.expected_release = expected_release
          wishlist.price = final_price
          wishlist.save

      
      end

       respond_to do |format|
        format.json { render :json => {"status":"ok"}  }
      end      
      

    rescue => error
      redirect_to wishlists_path, :alert=>error.message
#      puts error.message
    end
end

def move_from_wishlist
  begin
    @wishlist = Wishlist.find(params[:wishlist_id])

    @book = Book.new(:name=>@wishlist.name,:author_id=>@wishlist.author_id, :publisher_id=>@wishlist.publisher_id,:note=>@wishlist.note, :publish_year=>@wishlist.publish_year,:user_id=>@wishlist.user_id)

    if (@book.save)
      @wishlist.destroy

      respond_to do |format|
        format.json { render :json => {"status":"ok"}  }
      end
    else
      respond_to do |format|
        format.json { render :json => {"status":"nepodarilo sa presunúť záznam"}  }
      end
    end



  rescue=>error
    redirect_to wishlists_path, :alert=>error.message
  end
end

  def chart_total_wishlist

    @result = Wishlist.joins(:user).select("count(1) as value, users.name as label").group("users.name")           
              
    respond_to do |format|
      format.json {
        #render json: (status:"ok" , @result.to_json(:only=> [:label, :value]))
         render :json => {"status": "ok", "data": @result.to_json(:only=> [:label, :value]) }  
      }
    end

  end

  # POST /wishlists
  # POST /wishlists.json
  def create
    @wishlist = Wishlist.new(wishlist_params)

    respond_to do |format|
      if @wishlist.save
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully created.' }
        format.json { render :show, status: :created, location: @wishlist }
      else
        format.html { render :new }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishlists/1
  # PATCH/PUT /wishlists/1.json
  def update
    respond_to do |format|
      if @wishlist.update(wishlist_params)
        format.html { redirect_to @wishlist, notice: 'Wishlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @wishlist }
      else
        format.html { render :edit }
        format.json { render json: @wishlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlists/1
  # DELETE /wishlists/1.json
  def destroy
    @wishlist.destroy
    respond_to do |format|
      format.html { redirect_to wishlists_url, notice: 'Záznam vo wishliste bol úspešne zmazaný.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wishlist
      @wishlist = Wishlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wishlist_params
      params.require(:wishlist).permit(:name, :author_id, :publisher_id, :publish_year, :martinus_url, :image_url, :note, :pages, :price, :expected_release, :user_id)
    end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_form.html.erb
<%= form_with(model: wishlist, local: true) do |form| %>
  <% if wishlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wishlist.errors.count, "error") %> prohibited this wishlist from being saved:</h2>

      <ul>
      <% wishlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.text_field :author_id %>
  </div>

  <div class="field">
    <%= form.label :publisher_id %>
    <%= form.text_field :publisher_id %>
  </div>

  <div class="field">
    <%= form.label :publish_year %>
    <%= form.number_field :publish_year %>
  </div>

  <div class="field">
    <%= form.label :martinus_url %>
    <%= form.text_field :martinus_url %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_field :note %>
  </div>

  <div class="field">
    <%= form.label :pages %>
    <%= form.number_field :pages %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :expected_release %>
    <%= form.text_field :expected_release %>
  </div>

  <div class="field">
    <%= form.label :user_id_id %>
    <%= form.text_field :user_id_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wishlists/edit.html.erb
<h1>Editing Wishlist</h1>

<%= render 'form', wishlist: @wishlist %>

<%= link_to 'Show', @wishlist %> |
<%= link_to 'Back', wishlists_path %>

app/views/wishlists/index.html.erb
<p id="notice"><%= render 'layouts/flash_message' %></p>

<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Wishlist</h2>
    <ol class="breadcrumb">
      <li>
        <%= link_to 'Home', root_path %>
      </li>
      <li class="active">
        <strong>Wishlist</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">

  </div>
</div>


<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row margin35minus">
   <div class="col-lg-12 nopadding">
     <div class="ibox float-e-margins">
      <div class="ibox-content">
        <button type="button" class="btn btn-success" id="add_wishlist_button" data-toggle="modal" data-target="#addWishlistModal">Pridaj novú knihu do wishlistu</button> 
        <button type="button" class="btn btn-primary" id="update_martinus_button">Aktualizuj info z Martinusu</button>
        
        <hr>
         <div id="spinner_box" style="display:none">
           <div class="bookshelf_wrapper">
  <ul class="books_list">
    <li class="book_item first"></li>
    <li class="book_item second"></li>
    <li class="book_item third"></li>
    <li class="book_item fourth"></li>
    <li class="book_item fifth"></li>
    <li class="book_item sixth"></li>
  </ul>
  <div class="shelf"></div>
</div>
                </div>
        <div class="table-responsive main-box">
          <table class="table table-bordered" id="wishlists" style="width:100%">
  <thead>
    <tr>
      <th></th>
      <th>Názov</th>
      <th>Autor</th>
      <th>Vydavateľ</th>
      <th class="hidden-sm hidden-xs">Rok vydania</th>
      <th class="hidden-sm hidden-xs">Martinus url</th>
      <th class="hidden-sm hidden-xs">Poznámka</th>
      <th class="hidden-sm hidden-xs">Počet strán</th>
      <th class="hidden-sm hidden-xs">Cena</th>
      <th class="hidden-sm hidden-xs">Očakávaný dátum vydania</th>
      <th class="hidden-sm hidden-xs">Vložil</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @wishlists.each do |wishlist| %>
      <tr>
        <td><%= image_tag wishlist.image_url if wishlist.image_url.present? %></td>
        <td><%= wishlist.name %></td>
        <td><%= wishlist.author.name if wishlist.author.present? %></td>
        <td><%= wishlist.publisher.name if wishlist.publisher.present? %></td>
        <td class="hidden-sm hidden-xs"><%= wishlist.publish_year %></td>
        <td class="hidden-sm hidden-xs"><%= wishlist.martinus_url %></td>
        <td class="hidden-sm hidden-xs"><%= wishlist.note %></td>
        <td class="hidden-sm hidden-xs"><%= wishlist.pages %></td>
        <td class="hidden-sm hidden-xs"><%= wishlist.price %></td>
        <td class="hidden-sm hidden-xs"><%= wishlist.expected_release %></td>
        <td class="hidden-sm hidden-xs"><%= wishlist.user.name if wishlist.user.present? %></td>
        <td><a class="confirm_wishlist_table_btn"><i id="<%=wishlist.id%>" class="fa fa-check fa-2x" aria-hidden="true"></i></a></td>
          <td><a class="edit_wishlist_table_btn" data-toggle="modal" data-target="#editWishlistModal"><i id="<%=wishlist.id%>" class="fa fa-pencil-square-o fa-2x" aria-hidden="true"></i></a></td>
        <td><%= link_to  wishlist, method: :delete, data: { confirm: 'Naozaj ju chceš zmazať?' } do %><i class="fa fa-trash-o fa-2x" aria-hidden="true" ></i>  
                <% end %></td>
        </tr>
    <% end %>
  </tbody>
 </table>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<br>

<div id="addWishlistModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h2 class="modal-title" id="myModalLabel">Pridaj knihu </h2>
       
      </div>
      <div class="modal-body">
        <div class="alert alert-danger noborders">
   Aspoň jedno z polí vyznačených na červeno je povinné
  </div>
        <div class="form-group has-error">
            <label>Názov:</label><input type="text" name="wishlistname" id="wishlistname" class="form-control" placeholder="Názov" /><br>
            <label>Martinus URL:</label><input type="text" name="martinus_url" id="martinus_url" class="form-control" placeholder="URL" /><br>
            
            </div>
            <label>Autor:</label><%= select_tag 'author', options_from_collection_for_select(@authors, 'id', 'name'), class: 'form-control', id: 'author',prompt: "--vyber autora--" %><br>
             <label>Vydavateľ:</label><%= select_tag 'publisher', options_from_collection_for_select(@publishers, 'id', 'name'), class: 'form-control', id: 'publisher',prompt: "--vyber vydavateľa--" %><br>
            <label>Rok vydania:</label><input type="number" name="publish_year" id="publish_year" class="form-control" placeholder="Zadaj rok" /><br>
           <label>Poznámka:</label><input type="text" name="note" id="note" class="form-control" placeholder="Názov" /><br>
           
           
       
       <button id="addwishlistconfirm" type="button" class="addwishlist btn btn-success">Pridaj</button>
 
   </div>
 </div>
</div>
</div>

<div id="editWishlistModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h2 class="modal-title" id="myModalLabel">Uprav knihu </h2>
       
      </div>
      <div class="modal-body">
        <div class="alert alert-danger noborders">
   Aspoň jedno z polí vyznačených na červeno je povinné
  </div>
        <div class="form-group has-error">
           <input style="visibility:hidden" type="text" name="editwishlistID" id="editwishlistID" value="" readonly>
             <label>Názov:</label><input type="text" name="edit_wishlistname" id="edit_wishlistname" class="form-control" placeholder="Názov" /><br>
             <label>Martinus URL:</label><input type="text" name="edit_martinus_url" id="edit_martinus_url" class="form-control" placeholder="URL" /><br>
            </div>
             <label>Autor:</label><%= select_tag 'edit_author', options_from_collection_for_select(@authors, 'id', 'name'), class: 'form-control', id: 'edit_author',prompt: "--vyber autora--" %><br>
             <label>Vydavateľ:</label><%= select_tag 'edit_publisher', options_from_collection_for_select(@publishers, 'id', 'name'), class: 'form-control', id: 'edit_publisher',prompt: "--vyber vydavateľa--" %><br>
            <label>Rok vydania:</label><input type="number" name="edit_publish_year" id="edit_publish_year" class="form-control" placeholder="Zadaj rok" /><br>
           <label>Poznámka:</label><input type="text" name="edit_note" id="edit_note" class="form-control" placeholder="Názov" /><br>
           
           
           
           
       
       <button id="editwishlistconfirm" type="button" class="editwishlist btn btn-success">Uprav</button>
 
   </div>
 </div>
</div>
</div>

<script>
var wishlisttable;

var tableready = function() {

    $('.confirm_wishlist_table_btn').on('click',function(event){
          //console.log(event.target.id);
          $wishlist_id = event.target.id;
        if (!confirm('Chceš túto knihu presunúť z wishlistu do knižnice?')) return false;
          $.ajax({
            type: "POST",
            url: "/move_from_wishlist",
            data: {
              wishlist_id: $wishlist_id

            },

            success:function(data){
              if (data.status == "ok")
              {
                alert("Hotovo" );
                location.reload();
                
              }
              else { alert(data.status);}


            }
          });
          



        });



$('#update_martinus_button').on('click',function(event){
     
         $("#spinner_box").removeAttr("style");
        $("#main_box").addClass('ibox-content sk-loading');

$('#wishlists').hide();
$('#loader').show();         
 $.ajax({
  type: "POST",
  url: "/update_from_martinus",
  success:function(data) {
     if (data.status =="ok") {
       $("#main_box").removeClass('ibox-content sk-loading');
        $("#spinner_box").css({"display": "none"});  
      alert( "Dáta boli aktualizované");
      location.reload();
    }
    else {
     alert( "Nepodarilo sa aktualizovat dáta");
      location.reload(); 
    }
  
},
 error: function(msg){
   $("#main_box").removeClass('ibox-content sk-loading');
        $("#spinner_box").css({"display": "none"});
              alert("Nepodarilo sa stiahnuť údaje z martinus.sk");
            } 


    });


})

 wishlisttable= $('#wishlists').DataTable({
  'order': [2, 'desc'],
  'serverSide': false,
  'stateSave' :true,
  'dom': 'lfr<"pull-right">tip',
 /*'buttons': [
  {"extend" : 'copyHtml5',"text":"Copy","className": 'btn btn-default btn-xs'},
  {"extend" : 'excelHtml5',"text": "XLS","className": 'btn btn-default btn-xs'},
  {"extend" : 'csvHtml5',"text": "CSV","className": 'btn btn-default btn-xs'},

  {
    text: 'TXT',
    extend: 'csvHtml5',
    fieldSeparator: '\t',
    extension: '.txt',
    "className": 'btn btn-default btn-xs'
  },
  {"extend" : 'pdfHtml5',"text": "PDF","className": 'btn btn-default btn-xs'},

  ],*/
  'language': {
        'url': '/datatables_slovak.json'
      },
  'lengthMenu': [
  [10, 50,100, -1],
  [10, 50,100, "All"]
  ]

});

 $('.edit_wishlist_table_btn').on('click',function(event){

  //$wishlist_id=event.target.id;
  $wishlist_id = event.target.id;
$("#editwishlistID").val($wishlist_id);
   $.ajax({
            type: "GET",
            url: "/wishlists/"+$wishlist_id+".json",
           
            success:function(data){
             
             // console.log(data);
                                 
             $("#edit_wishlistname").val(data.name); 
             if (data.author_id !== null) { $("#edit_author").val(data.author_id); }
             if (data.publisher_id !== null) { $("#edit_publisher").val(data.publisher_id); }
             $("#edit_publish_year").val(data.publish_year); 
             $("#edit_note").val(data.note); 
             $("#edit_martinus_url").val(data.martinus_url); 
              


            },
            error: function(msg){
              alert(msg);
            }
          });


 });


$('.editwishlist').on('click',function(event){
          //console.log(event.target.id);
          
          $wishlist_id = $("#editwishlistID").val();
          $name = $('#edit_wishlistname').val();
          $author = $('#edit_author').val();
          $publisher = $('#edit_publisher').val();
          $publish_year = $('#edit_publish_year').val();
          $note = $('#edit_note').val();
          $martinus_url = $("#edit_martinus_url").val(); 
         

              $.ajax({
            type: "POST",
            url: "/modal_edit_wishlist",
             data: {
              wishlistID: $wishlist_id,
              name: $name,
              author: $author,
              publisher: $publisher,
              publish_year: $publish_year,
              note: $note,
              martinus_url: $martinus_url

            },
         

            success:function(data){
              if (data.status == "ok")
              {
                alert("Záznam vo wishliste bol upravený" );
                location.reload();
              }
              else { alert("Error");}


            }
          });
          



        });

$('.addwishlist').on('click',function(event){
          //console.log(event.target.id);
          
          $name = $('#wishlistname').val();
          $author = $('#author').val();
          $publisher = $('#publisher').val();
          $publish_year = $('#publish_year').val();
          $note = $('#note').val();
          $martinus_url = $("#martinus_url").val(); 
                  

              $.ajax({
            type: "POST",
            url: "/modal_create_wishlist",
            data: {
              name: $name,
              author: $author,
              publisher: $publisher,
              publish_year: $publish_year,
              note: $note,
              martinus_url: $martinus_url

             },

            success:function(data){
              if (data.status == "ok")
              {
                alert("Záznam vo wishliste bol vytvorený" );
                location.reload();
              }
              else { alert(data.status);}


            }
          });
          



        });


};
$(".wishlists.index").ready(tableready);


document.addEventListener('turbolinks:before-cache', function() {
 if ($('#wishlists_wrapper').length ==1) {wishlisttable.destroy() ;} 

});


$(".wishlists.index").on('turbolinks:load', tableready); 
</script>

app/views/wishlists/new.html.erb
<h1>New Wishlist</h1>

<%= render 'form', wishlist: @wishlist %>

<%= link_to 'Back', wishlists_path %>

app/views/wishlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wishlist.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= @wishlist.author %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @wishlist.publisher %>
</p>

<p>
  <strong>Publish year:</strong>
  <%= @wishlist.publish_year %>
</p>

<p>
  <strong>Martinus url:</strong>
  <%= @wishlist.martinus_url %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @wishlist.image_url %>
</p>

<p>
  <strong>Note:</strong>
  <%= @wishlist.note %>
</p>

<p>
  <strong>Pages:</strong>
  <%= @wishlist.pages %>
</p>

<p>
  <strong>Price:</strong>
  <%= @wishlist.price %>
</p>

<p>
  <strong>Expected release:</strong>
  <%= @wishlist.expected_release %>
</p>

<p>
  <strong>User:</strong>
  <%= @wishlist.user_id %>
</p>

<%= link_to 'Edit', edit_wishlist_path(@wishlist) %> |
<%= link_to 'Back', wishlists_path %>