config/routes.rb
Rails.application.routes.draw do

  resources :wishlists
   mount LetsencryptPlugin::Engine, at: '/'  # It must be at root level


  devise_for :users, :controllers => {:sessions => "users/sessions", :registrations => "users/registrations"}, :skip => [:registrations]
  
  devise_scope :user do
    match 'users/:id' => 'users/registrations#destroy', :via => :delete, :as => :admin_destroy_user
    post 'modal_edit_user' => 'users/registrations#modal_edit_user', :as => 'modal_edit_user'
    post 'modal_create_user' => 'users/registrations#modal_create_user', :as => 'modal_create_user'
    get 'users/edit' => 'users/registrations#edit', :as => 'edit_user_registration'    
    patch 'users' => 'users/registrations#update', :as => 'user_registration'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 resources :books
 resources :publishers
 resources :authors

 get 'static_pages/home'
 get '/uzivatelia' => 'static_pages#users', :as => 'users'

 #authors
 post '/modal_create_author' => 'authors#modal_create_author', :as=> 'modal_create_author'
 post '/modal_edit_author' => 'authors#modal_edit_author', :as=> 'modal_edit_author'
  
 #publishers
 post '/modal_create_publisher' => 'publishers#modal_create_publisher', :as=> 'modal_create_publisher'
 post '/modal_edit_publisher' => 'publishers#modal_edit_publisher', :as=> 'modal_edit_publisher'

 #books
 post '/modal_create_book' => 'books#modal_create_book', :as=> 'modal_create_book'
 post '/modal_edit_book' => 'books#modal_edit_book', :as=> 'modal_edit_book'
 get '/chart_total_books' => 'books#chart_total_books', :as=> 'chart_total_books'
 get '/chart_top_book_publishers' => 'books#chart_top_book_publishers', :as=> 'chart_top_book_publishers'
 get '/chart_top_book_authors' => 'books#chart_top_book_authors', :as=> 'chart_top_book_authors'

#wishlists
post '/modal_create_wishlist' => 'wishlists#modal_create_wishlist', :as=> 'modal_create_wishlist'
post '/modal_edit_wishlist' => 'wishlists#modal_edit_wishlist', :as=> 'modal_edit_wishlist'
post '/update_from_martinus' => 'wishlists#update_from_martinus', :as=> 'update_from_martinus'
post '/move_from_wishlist' => 'wishlists#move_from_wishlist', :as=> 'move_from_wishlist'
get '/chart_total_wishlist' => 'wishlists#chart_total_wishlist', :as=> 'chart_total_wishlist'

  root 'static_pages#home'
end

app/views/layouts/_flash_message.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="alert <%= flash_class(key).to_s %> fade in">
    
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
 <div class="footer">
                    <div class="pull-right">
                       
                    </div>
                    <div>
                        <strong>Copyright</strong> BlackRuby &copy; 2019
                    </div>
                </div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            
            <a class="navbar-minimalize minimalize-styl-2 btn btn-success " ><i class="fa fa-bars"></i> </a>
        
        
        </div>

            <ul class="nav navbar-top-links navbar-right">

        

       

         
           


                <li>
                    <i class="fa fa-sign-out"></i>
                    <%= content_tag(:li, link_to('Logout', destroy_user_session_path, method: :delete)) %> 
                         
                        
                    
                </li>
              
            </ul>

        </nav>

app/views/layouts/_sidebar.html.erb
 <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element"> 
                          
                          
                         
                          <span>
                          <img class="center img-responsive img-circle" src="<%= asset_path( 'user-avatar.png' ) %>"  alt="profile_img">
                            
                            
                             </span>
                            
                            <span class="clear"> <span class="block m-t-xs"> <center><strong class="font-bold">
                               
                                 <h4 ><%= current_user.email %></h4>
                                
                                 
                             </strong></center>
                           
                        </div>
                      </li>
                    
                            <li><%= link_to root_path, data: { turbolinks: false } do%><i class="fa fa-bar-chart" aria-hidden="true"></i> <span class="nav-label">Prehľad</span><%end%></li>
                            <li><%= link_to books_path do %><i class="fa fa-book" aria-hidden="true"></i> <span class="nav-label">Knihy</span><%end%></li>
                            <li><%= link_to wishlists_path do%><i class="fa fa-shopping-basket" aria-hidden="true"></i> <span class="nav-label">Wishlist</span><%end%></li>
                            <li><%= link_to authors_path do%><i class="fa fa-users" aria-hidden="true"></i> <span class="nav-label">Autori</span><%end%></li>
                            <li><%= link_to  publishers_path do %><i class="fa fa-print" aria-hidden="true"></i> <span class="nav-label">Vydavateľstvá</span><%end%></li>
                            <li><%= link_to users_path do%><i class="fa fa-user" aria-hidden="true"></i> <span class="nav-label">Užívatelia</span><%end%></li>
                                   
                            
                            
              

                       
                    
                   
                </ul>

            </div>
        </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kniznica</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8"> 
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="Naša knižnica">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta name="author" content="BlackRuby s.r.o.">
    
  <% if content_for?(:head_attributes) %>
    <%= yield(:head_attributes) %> 
  <% end %>
</head>
<% if user_signed_in? %>   
<body class="<%= controller_name %> <%= action_name %> pace-done"
  <% if content_for?(:body_attributes) %>
    <%= yield(:body_attributes) %> 
  <% end %>
  >
  <div id="wrapper">
        <!--<div id="page-wrapper" class="gray-bg">-->
    
 <%= render 'layouts/sidebar' %>
 
 <div id="page-wrapper" class="gray-bg dashbard-1" style="min-height: 1181px;">
        <div class="row border-bottom">
 
 <%= render 'layouts/header' %>
 
</div>
<div class="wrapper wrapper-content">
         <!--   <div class="container">-->

           
<%= yield %>


  <!--</div>-->

    
</div>

<%= render 'layouts/footer' %>

</div>



</div>


</body>
<% else %>




<body class="gray-bg">
<p id="notice"><%= render 'layouts/flash_message' %></p>
    <div class="middle-box text-center loginscreen animated fadeInDown">
        <div>
            <div style="margin-left: -40px">

              <!--  <h1 class="logo-name">SO+</h1>-->
              
            </div>
            <h3>Kniznica</h3>
            <p>Prihlás sa emailom</p>
            <%= yield %>
            <p class="m-t"> <small>BlackRuby &copy; 2019</small> </p>
        </div>
    </div>

   
</body>
<% end %>
</html>